### ISSUE TITLE
EC2 임시 배포

### ISSUE THREAD

**Issue by suhsein** [suhsein/OwnSpace#50]
Aws EC2로 임시 배포 해본다.

**Comment by suhsein** [comment]
> ## EC2 인스턴스 생성하기
Aws 콘솔에서 EC2 접속 후, 인스턴스 시작 클릭
1. 이름 설정
   -> 어플리케이션 이름으로 설정
1. 애플리케이션 및 OS 이미지(Amazon Machine Image) 
    -> 우분투로 설정
1. 인스턴스 유형
    -> t2.micro로 설정
1. 키페어 
    -> 없다면 새로 생성하고, 있다면 기존 것을 사용함. 반드시 pem 파일이 유출되지 않도록 잘 관리해야한다.
1. 네트워크 설정
    -> 보안그룹 생성. 모든 위치에서 SSH 트래픽 허용
1. 스토리지 구성
    -> 10GiB로 설정
인스턴스 시작 클릭
인스턴스 생성에는 시간이 조금 소요된다.

> ## 인스턴스 보안 그룹 규칙 변경하기

인스턴스를 선택하고 보안 그룹을 볼 수 있다. 보안 그룹에 들어가서 인바운드 규칙을 편집한다.
보안그룹에 의해 접속이 제한되므로 꼭 설정해주어야한다.
80포트(http), 8080포트(http), 22포트(ssh), 5000포트(사용자 지정) -> IPv4 Anywhere
규칙 추가 후, 저장한다. 

> ## RDS로 DB 생성하기
 DB도 사용해야 하므로, RDS에 접속해서 DB도 생성한다. 
1. 데이터 베이스 생성방식
    -> 표준생성 선택
1. 엔진유형
    -> 사용하는 엔진 옵션 선택. MySQL로 선택함. 사용하는 버전에 맞춰서 선택
1.  템플릿
    -> 프리티어 선택
1. 설정
    -> db 식별자, 사용자 이름, 암호, 암호 확인을 입력한다. DB 접속 시 사용하게 되는 이름과 암호이다.
1. 인스턴스 구성
    -> t2.micro 사용
1.  스토리지
    -> 기본 설정 사용
1. 연결
    -> 기본 설정 사용
1. 데이터베이스 인증
    -> 암호 인증 선택
1. 모니터링
    -> 체크 해제
1. 추가 구성
    -> 초기 데이터베이스 이름 설정. 데이터베이스 내부의 데이터베이스 이름을 지정한다. 나머지는 기본 설정 사용
데이터베이스 생성 클릭

> ## DB 보안 그룹 규칙 변경하기
생성한 DB의 보안그룹을 선택한다.
MySQL/Aurora에 대해 3306포트의 접근을 Anywhere로 설정해준다.

> ## 인스턴스 연결하기
인스턴스에 우클릭하여 연결을 클릭하고, SSH 클라이언트 탭에 들어가면, SSH에서 인스턴스에 연결하는 방법이 설명되어 있다.
bash를 켜고(Git bash 사용함) 다음 명령어들을 입력한다.

``` 
java -version // 자바 버전 확인. 없다면 설치

// 자바 설치 명령어
sudo apt update
sudo apt install openjdk-17-jre-headless

// pem 파일에 권한 주기
chmod 400 pem파일명

// 인스턴스에 연결 (위의 인스턴스에 연결하는 방법에서 명령어를 복사할 수 있다.)
ssh -i pem파일명 ubuntu@인스턴스개방주소

```
> ## 설정 파일 수정하기

application.yml 혹은 application.properties 수정이 필요하다.
1. db url 수정하기
 -> RDS 콘솔에서 생성했던 DB에 들어가서 엔드포인트를 복사한다. 이를 사용하여 수정한다.
1. dialect 지정하기
 -> IDE에서는 자동으로 dialect 처리를 해주었으나, 인스턴스에서 실행하게 될 경우 인식을 못하므로 명시적으로 dialect를 지정해줘야한다. 

```
spring:
  datasource:
    url: jdbc:mysql://엔드포인트주소:3306/ownspace?serverTimezone=Asia/Seoul
    username: root
    password: ${my_sql_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none   # create # 스키마 자동생성. 개발 환경에서만 사용
      dialect: org.hibernate.dialect.MySQLDialect  # 추가
    properties:
      hibernate:
        format_sql: true
    database: mysql  # 추가
    database-platform: org.hibernate.dialect.MySQLDialect  # 추가
```

> ## 프로젝트 빌드하기

인텔리제이를 사용했으므로, 인텔리제이에서 터미널을 켜고 다음 명령어를 입력한다

```
./gradlew build
```
빌드가 완료되고,  프로젝트 폴더 내부의 build/libs에 스냅샷 jar 파일이 저장된다.
SNAPSHOT.jar로 끝나는 파일을 바탕화면에 두고, bash를 하나 더 켠다.
로컬 pc의 파일을 원격 인스턴스로 보내는 명령어를 입력한다.

```
// pem 파일에 권한 주기
chmod 400 pem파일명

// 원격 인스턴스로 파일 전송하기. 콜론 이하는 인스턴스에서 전송된 파일이 저장되는 경로이다
scp -i pem파일명 스냅샷파일경로/스냅샷파일명 ubuntu@인스턴스개방주소:~/
```

> ## 환경변수 설정하기
그 전에 IDE에서 사용하던 환경변수가 있다면 환경변수를 먼저 지정해줘야 한다.
연결된 인스턴스 bash 창에서 다음 명령어를 입력한다. 환경변수는 전역변수로 설정해줘야한다. 

```
// 환경변수 설정(전역)
vi /etc/environment

// vi 창 내에서 입력 후 저장(필요한 환경변수들을 모두 입력함)
export 변수명=값

// 환경변수 적용
source /etc/environment 
```
> ## 포트 포워딩 하기 
필요에 따라서 인스턴스 bash 창에서 다음 명령어를 입력한다. 
어플리케이션 설정에서 5000번 포트로 설정했기 때문에 포트포워딩이 필요하다.

```
// 80번 포트 접속 시 5000번으로 자동연결 하도록 포워딩
sudo iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-port 5000
```

> ## jar 파일 실행하기
인스턴스 bash 창에서 다음 명령어를 입력하여 실행할 수 있다.
```
sudo java -jar jar파일명 
```

> ## 접속하기
https가 아닌, http://를 앞에 꼭 붙여줘야한다.
퍼블릭 IPv4 주소 혹은 퍼블릭 IPv4 DNS로 접속한다. (웹에서 프라이빗 IPv4 주소로 접속하면 접속이 안된다.)


---
ec2 인스턴스 생성과 관련된 정보 참고 https://youtu.be/fBzR6DqP5jk?si=h0ps5dX4P2F7fHKv
rds db 생성과 관련된 정보 참고 https://www.youtube.com/watch?v=DG4qwH9bUYA
